#Is the following code legal?
try :
x = 1
finally:
print(“finally”)
#Yes, try can come with except & finally / finally